"""empty message

Revision ID: 019f405c0d75
Revises: 39005a50ac2d
Create Date: 2022-08-13 06:52:15.147808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019f405c0d75'
down_revision = '39005a50ac2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_aritist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'aritist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('aritist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_aritist_id_fkey', 'Show', 'Artist', ['aritist_id'], ['id'])
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
