"""empty message

Revision ID: 5f90c3a519cf
Revises: f59f50445d71
Create Date: 2022-08-07 14:37:47.791855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f90c3a519cf'
down_revision = 'f59f50445d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('Website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_venue')
    op.drop_column('Venue', 'Website_link')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
