"""empty message

Revision ID: c010b793f151
Revises: 5f90c3a519cf
Create Date: 2022-08-07 14:49:19.510569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c010b793f151'
down_revision = '5f90c3a519cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('Website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'Website_link')
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
